// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelPackaging() {
  return window['go']['main']['App']['CancelPackaging']();
}

export function ChangeProjectRoot(arg1) {
  return window['go']['main']['App']['ChangeProjectRoot'](arg1);
}

export function CountModules() {
  return window['go']['main']['App']['CountModules']();
}

export function CurrentBranch() {
  return window['go']['main']['App']['CurrentBranch']();
}

export function GetChangedFiles(arg1) {
  return window['go']['main']['App']['GetChangedFiles'](arg1);
}

export function GetCommitDiff(arg1) {
  return window['go']['main']['App']['GetCommitDiff'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetFileDiff(arg1, arg2) {
  return window['go']['main']['App']['GetFileDiff'](arg1, arg2);
}

export function GetInitialState() {
  return window['go']['main']['App']['GetInitialState']();
}

export function GetModuleGraph() {
  return window['go']['main']['App']['GetModuleGraph']();
}

export function GetTimingSnapshot() {
  return window['go']['main']['App']['GetTimingSnapshot']();
}

export function HasMaven() {
  return window['go']['main']['App']['HasMaven']();
}

export function ListBranches() {
  return window['go']['main']['App']['ListBranches']();
}

export function ListCommits(arg1) {
  return window['go']['main']['App']['ListCommits'](arg1);
}

export function PatchConfig(arg1) {
  return window['go']['main']['App']['PatchConfig'](arg1);
}

export function PickDirectory(arg1, arg2) {
  return window['go']['main']['App']['PickDirectory'](arg1, arg2);
}

export function RefreshProject() {
  return window['go']['main']['App']['RefreshProject']();
}

export function ResolveImpactedModules(arg1, arg2) {
  return window['go']['main']['App']['ResolveImpactedModules'](arg1, arg2);
}

export function StartLoadCommits(arg1) {
  return window['go']['main']['App']['StartLoadCommits'](arg1);
}

export function StartPackaging(arg1) {
  return window['go']['main']['App']['StartPackaging'](arg1);
}

export function SwitchBranch(arg1) {
  return window['go']['main']['App']['SwitchBranch'](arg1);
}

export function ValidateOutputDir(arg1) {
  return window['go']['main']['App']['ValidateOutputDir'](arg1);
}
