// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {git} from '../models';
import {config} from '../models';
import {maven} from '../models';
import {timing} from '../models';

export function CancelPackaging():Promise<boolean>;

export function ChangeProjectRoot(arg1:string):Promise<main.InitialStateDTO>;

export function CountModules():Promise<number>;

export function CurrentBranch():Promise<string>;

export function GetChangedFiles(arg1:string):Promise<Array<string>>;

export function GetCommitDiff(arg1:string):Promise<git.CommitDiff>;

export function GetConfig():Promise<config.Config>;

export function GetFileDiff(arg1:string,arg2:string):Promise<git.FileDiff>;

export function GetInitialState():Promise<main.InitialStateDTO>;

export function GetModuleGraph():Promise<maven.ModuleGraph>;

export function GetTimingSnapshot():Promise<timing.Summary>;

export function HasMaven():Promise<boolean>;

export function ListBranches():Promise<Array<string>>;

export function ListCommits(arg1:number):Promise<Array<git.Commit>>;

export function PatchConfig(arg1:Record<string, any>):Promise<config.Config>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function RefreshProject():Promise<main.InitialStateDTO>;

export function ResolveImpactedModules(arg1:Array<string>,arg2:boolean):Promise<main.ImpactDTO>;

export function StartLoadCommits(arg1:number):Promise<void>;

export function StartPackaging(arg1:main.StartPackagingOpts):Promise<void>;

export function SwitchBranch(arg1:string):Promise<main.SwitchBranchResult>;

export function ValidateOutputDir(arg1:string):Promise<void>;
